version: '3'
services:
  db:
    restart: always
    image: "postgres:10"
    ports:
      - "3000:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - env_file
    networks:
      - db_nw
  flaskapp:
    restart: always
    build: .
    env_file:
      - env_file
    ports:
    - "5000:5000"
    volumes:
      - .:/opt/services/flaskapp/src
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db
    entrypoint: ["python", "manage.py","runserver"]
  nginx:
    restart: always
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - flaskapp
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
  postgres-data: